export const ConstantType = {
  TOGGLE_TODO: "TOGGLE_TODO",
  SAVE_TODO: "SAVE_TODO",
  FETCH_TODOS: "FETCH_TODOS",
  DELETE_TODO: "DELETE_TODO",
  TODO_ADD: "TODO_ADD",
  TODOS_LOAD: "TODOS_LOAD",
  CURRENT_UPDATE: "CURRENT_UPDATE",
  TODO_REPLACE: "TODO_REPLACE",
  TODO_REMOVE: "TODO_REMOVE",
};
